# Code written by ChatGPT

import pandas as pd
# Data provided
data = [
    ("Aya Abdelrahman", 5, "Student"),
    ("Wahideh Achbari", None, "Staff"),
    ("Bissola Adenekan", 1, "Student"),
    ("Roland Adorjani", None, "Staff"),
    ("Shriya Agrawal", 5, "Student"),
    ("Gizem Aktas", None, "Staff"),
    ("Ava Ali", 1, "Student"),
    ("Sean Almeida", 2, "Student"),
    ("Lukas Ansteeg", None, "Staff"),
    ("Maja Arament", 2, "Student"),
    ("Theo Araujo", None, "Staff"),
    ("Gadis Arumcitta Gadis Masita", 3, "Student"),
    ("Dorottya Báldy", 4, "Student"),
    ("Lotte Becking", 4, "Student"),
    ("Gabriella Beckley", 3, "Student"),
    ("Alejandro Berges Coronel", 3, "Student"),
    ("Julius Bijkerk", None, "Staff"),
    ("Emma-Rose Blacher", 2, "Student"),
    ("Rasmus Blichfeldt", 1, "Student"),
    ("Tommy Blomvliet", None, "Staff"),
    ("Penelope Bollini", None, "Staff"),
    ("Lumi Borgers", 5, "Student"),
    ("Christal Breinburg", 1, "Student"),
    ("Irene Bressanello", 2, "Student"),
    ("Anouk Buijs", 5, "Student"),
    ("Volodymyr Butko", 4, "Student"),
    ("Catherin Catherin Andiani", 1, "Student"),
    ("Alva Chen", 4, "Student"),
    ("Roy Chen", 3, "Student"),
    ("Nikko Chy", 3, "Student"),
    ("Ana Contreras Estrada", 2, "Student"),
    ("Walter Contreras Estrada", 5, "Student"),
    ("Brendan Corcoran", 4, "Student"),
    ("Joeben Davis", 5, "Student"),
    ("Philine Dekker", 1, "Student"),
    ("Maria Dumitru", 5, "Student"),
    ("Farah Elhusseini", 1, "Student"),
    ("Alexandru Enache", 2, "Student"),
    ("Wentao Fan", 3, "Student"),
    ("Felicia Felicia Christy Leo", 3, "Student"),
    ("Jacco Friedeberg", 2, "Student"),
    ("Márton Gera", None, "Staff"),
    ("Callum Ginsburg", 4, "Student"),
    ("Angelica Goetzen", None, "Staff"),
    ("Ömer Gökçe", 2, "Student"),
    ("Alon Goodall", None, "Staff"),
    ("Kimiya Gräfin Zu Eltz", 2, "Student"),
    ("mirre Grouls", 1, "Student"),
    ("Davide Hanna", 5, "Student"),
    ("Leon Heemskerk", 5, "Student"),
    ("Barbara ten Hoedt", None, "Staff"),
    ("Micay van Hoogdalem", 3, "Student"),
    ("Andre Hua", 2, "Student"),
    ("Calson Huang", 5, "Student"),
    ("Adam Humphreys", 1, "Student"),
    ("Elnara Ibrahimli", 3, "Student"),
    ("Angela Iversen", 4, "Student"),
    ("Mana Iwasaki", 3, "Student"),
    ("Khushi Jain", 4, "Student"),
    ("Regina Jarillo Romo", 4, "Student"),
    ("Ilias Jelasity", 5, "Student"),
    ("Danielius Jonaitis", 4, "Student"),
    ("Sophia Khinchikashvili", 5, "Student"),
    ("Scarlett Kim", 1, "Student"),
    ("Sina Kitapci", 3, "Student"),
    ("Anna Klinker", 5, "Student"),
    ("Markus Knell", 5, "Student"),
    ("Maximilian Koch", 1, "Student"),
    ("Tadas Kraujalis", 3, "Student"),
    ("Akira Kuno", 4, "Student"),
    ("Jamie Lee", 2, "Student"),
    ("Daniel Lefenda Lefenda", 3, "Student"),
    ("David Liebmann", 4, "Student"),
    ("Noel Lilliestielke", 4, "Student"),
    ("Yujia Liu", 2, "Student"),
    ("Gabriela Mahecha Califa", 4, "Student"),
    ("Rafael Mantoani", 1, "Student"),
    ("Daniel Mayerhoffer", None, "Staff"),
    ("Maartje Meijers", None, "Staff"),
    ("Josy Mertens", 1, "Student"),
    ("Kazuya Nagai", 4, "Student"),
    ("Lucas Nagtegaal", 5, "Student"),
    ("Eugenia Natasha", None, "Staff"),
    ("Koyo Natsume", 2, "Student"),
    ("Alexia Nichifor", 3, "Student"),
    ("Viktor Nobel", 3, "Student"),
    ("Dasha Opoku-Gyamfi", 5, "Student"),
    ("Clement Paitrault", 3, "Student"),
    ("Lisa van Pappelendam", None, "Staff"),
    ("Viggo Pauw", 2, "Student"),
    ("Laura Peirs", None, "Staff"),
    ("Thaïss Petit", 5, "Student"),
    ("Steven Pickering", None, "Staff"),
    ("Diogo da Piedade Baptista", 3, "Student"),
    ("Thomas Poell", None, "Staff"),
    ("Gaspar Prieto Pote Monteiro Nogueira", 3, "Student"),
    ("Abhijit Raghu", 1, "Student"),
    ("Asjfaaq Razab-Sekh", 4, "Student"),
    ("Leon van Rooijen", None, "Staff"),
    ("Alexandra Roskam", 3, "Student"),
    ("Cem Şahingiray", 4, "Student"),
    ("Maria Sałasińska", 1, "Student"),
    ("Federico Santi", 2, "Student"),
    ("Nia Sas", 1, "Student"),
    ("Melody Scales", 2, "Student"),
    ("Michelle Schimmel", None, "Staff"),
    ("Bianka Śledzińska", 5, "Student"),
    ("Porter Stacy", 1, "Student"),
    ("Nojus Stankevičius", 1, "Student"),
    ("Anna Szwedowska", 1, "Student"),
    ("Emilie Taffouraud", 5, "Student"),
    ("Lucia Tanco Alonso", 2, "Student"),
    ("Mark Temchenko", 3, "Student"),
    ("Antonín Tesař", 4, "Student"),
    ("Niki Thrasyvoulou", 4, "Student"),
    ("Kaleem Ullah", None, "Staff"),
    ("Diliara Valeeva", None, "Staff"),
    ("Antonio Vasto", 4, "Student"),
    ("Rick Verplanke", None, "Staff"),
    ("Merijn Vervoorn", 3, "Student"),
    ("Emma Verweij", None, "Staff"),
    ("Juliette Visser", 2, "Student"),
    ("Bey Vongpatanasin", 5, "Student"),
    ("Weizhao Wang", 2, "Student"),
    ("David Wild", 1, "Student"),
    ("Rens Wilderom", None, "Staff"),
    ("Kim van Winsen", None, "Staff"),
    ("Collins Woodbleach", 1, "Student"),
    ("Wu Ke Wu", 5, "Student"),
    ("Derrick Wyckelsma", 2, "Student"),
    ("Sihun You", 3, "Student"),
    ("In Hyeok Youn", 2, "Student"),
    ("Shuting Yu", 4, "Student"),
    ("Marwan Zeinalabidin", 4, "Student"),
    ("Meng Zhao", 1, "Student"),
    ("Fleming Ziehm", 5, "Student")
]
# Creating a DataFrame
df_students = pd.DataFrame(data, columns=["Name", "Learning Team", "Role"])

# Filtering out non-student entries
df_students = df_students[df_students["Role"] == "Student"]

# Extracting first names
df_students["First Name"] = df_students["Name"].apply(lambda x: x.split()[0])

# Selecting the columns to be included in the CSV
df_students_final = df_students[["First Name", "Learning Team"]]

# Creating the CSV file in the local path
csv_path = "Student_Learning_Teams.csv"  # Save to the current directory
df_students_final.to_csv(csv_path, index=False)

print(f"CSV file saved at: {csv_path}")
